server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.blockchainpro: debug

